FROM node:11
    

ENV HOME=/src/inali-frontend


WORKDIR $HOME


#Copying package.json to Docker Image
COPY . .

#Installing all dependencies.
RUN npm install

# Running the dev server.
CMD ["npm", "run", "dev"]